### PR TITLE
Add Woodpecker CI support

### PR DESCRIPTION
**Pull request by 6543**
https://woodpecker-ci.org

### CODE REVIEW

**Comment by 6543** [comment]
@ukd1 :wave: :)

**Comment by 6543** [comment]
@ukd1 gentle ping :)

if you need something just tell

**Comment by 6543** [comment]
mentioned npm lib already got support: https://github.com/npm/ci-detect/releases/tag/v3.0.0

**Comment by ukd1** [comment]
@6543 all good, merging.

**Pull request merged**
